[workspace]
members = [
  "crates/lair_keystore",
  "crates/lair_keystore_api",
  "crates/lair_keystore_client",
]

[patch.crates-io]
tokio = { git = "https://github.com/tokio-rs/tokio.git", branch = "v0.2.x" }
