name: binary tests

on: [ push ]

jobs:

 test:
  runs-on: ${{ matrix.os }}
  strategy:
   matrix:
    os: [
     ubuntu-latest,
     macos-latest,
     # @todo windows support
     # windows-latest
    ]
    toolchain: [ stable ]
  steps:
   - uses: actions/checkout@v2
   - uses: actions-rs/toolchain@v1
     with:
       toolchain: ${{ matrix.toolchain }}

   # the binary can't be fully tested without an install
   - uses: actions-rs/cargo@v1
     with:
       command: install
       args: -f --path crates/lair_keystore

   # run the binary tests
   - uses: actions-rs/cargo@v1
     with:
       command: test
       args: --release --features="bin_tests"
