name: standard tests

on: [push]

jobs:
 test-linux:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: actions-rs/toolchain@v1
     with:
       toolchain: 1.45.1
   - uses: actions-rs/cargo@v1
     with:
       command: build
       args: --release --all-features

 test-mac:
  runs-on: macos-latest
  steps:
   - uses: actions/checkout@v2
   - uses: actions-rs/toolchain@v1
     with:
       toolchain: 1.45.1
   - uses: actions-rs/cargo@v1
     with:
       command: build
       args: --release --all-features

 test-win:
  runs-on: windows-latest
  steps:
   - uses: actions/checkout@v2
   - uses: actions-rs/toolchain@v1
     with:
       toolchain: 1.45.1
   - uses: actions-rs/cargo@v1
     with:
       command: build
       args: --release --all-features
