name: clippy

on: [push]

jobs:
 clippy:
  runs-on: ${{ matrix.os }}
  strategy:
   matrix:
    os: [ ubuntu-latest, macos-latest, windows-latest ]
    toolchain: [ nightly, stable, 1.45.1 ]
  steps:
   - uses: actions/checkout@v2
   - uses: actions-rs/toolchain@v1
     with:
       toolchain: ${{ matrix.toolchain }}
   - uses: actions-rs/cargo@v1
     with:
       command: clippy
