name: clippy

on: [push]

jobs:
 fmt:
  runs-on: ${{ matrix.os }}
  strategy:
   # don't build a crazy matrix just for fmt and clips
   matrix:
    os: [ ubuntu-latest ]
    toolchain: [ stable ]
  steps:
   - uses: actions/checkout@v2
   - uses: actions-rs/toolchain@v1
     with:
       toolchain: ${{ matrix.toolchain }}
       components: rustfmt, clippy
   - uses: actions-rs/cargo@v1
     with:
       command: fmt
       args: -- --check
   - uses: actions-rs/cargo@v1
     with:
       command: clippy
