name: standard tests

on: [push]

jobs:
 test:
  runs-on: $
  strategy:
   matrix:
    os: [ ubuntu-latest, macos-latest, windows-latest ]
  steps:
   - uses: actions/checkout@v2
   - uses: actions-rs/toolchain@v1
     with:
       toolchain: 1.45.1
   - uses: actions-rs/cargo@v1
     with:
       command: test
       args: --release --all-features
