name: test

on: [push]

jobs:

 fmt:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: actions-rs/toolchain@v1
     with:
      toolchain: stable
      components: rustfmt, clippy
   - uses: actions-rs/cargo@v1
     with:
      command: fmt
      args: -- --check
   - uses: actions-rs/cargo@v1
     with:
      command: clippy

 test:
  runs-on: ${{ matrix.os }}
  strategy:
   matrix:
    os: [ ubuntu-latest, macos-latest, windows-latest ]
    toolchain: [ stable, 1.45.1 ]
  steps:
   - uses: actions/checkout@v2
   - uses: actions-rs/toolchain@v1
     with:
       toolchain: ${{ matrix.toolchain }}

   # smoke test a release build
   - uses: actions-rs/cargo@v1
     with:
       command: build
       args: --release --all-features

   # the binary can't be fully tested without a debug install
   - uses: actions-rs/cargo@v1
     with:
       command: install
       args: --debug -f --path crates/lair_keystore

   # run all the tests
   - uses: actions-rs/cargo@v1
     with:
       command: test
       args: --release --all-features
